move logic to mapper
baihui212/tsharding pull request #14
Opened 2017-01-10 09:35 UTC by bobxwang

分库分表逻辑上移到各自Mapper中

2017-02-03 09:59 UTC, baihui212 requested changes
再看看批注，一起研讨一下

2017-02-03 09:59 UTC, baihui212 commented on tsharding-client/src/main/java/com/mogujie/trade/db/MapperRoutingHandler.java
> +    String SchemaName(Long shardingPara);
方法名注意要用小写开头

2017-02-03 09:59 UTC, baihui212 commented on tsharding-client/src/main/java/com/mogujie/trade/tsharding/route/orm/MapperResourceEnhancer.java
> +                        if (!text.contains(baseTableName)) {
这个if逻辑可以干掉了。之前蘑菇街在切换时，有TradeOrder和XDOrder两套表。TradeOrder单库单表，XDOrder、XDOrderXXX（扩展表等）要分表。所以有这个兼容逻辑。

2017-02-03 09:59 UTC, baihui212 commented on tsharding-client/src/main/java/com/mogujie/trade/tsharding/route/orm/MapperResourceEnhancer.java
> +                if (!sql.contains(baseTableName)) {
这里也一样。可能要换成有没有routingHandler的判断逻辑

2017-02-03 09:59 UTC, baihui212 commented on tsharding-client/src/main/java/com/mogujie/trade/db/DataSourceRouting.java
> +    Class<? extends MapperRoutingHandler> mapper() default MapperRoutingHandler.EmptyMapperRoutingHandler.class;
不建议在DataSourceRouting分库路由器里加分表路由的内容。建议新开一个注解TableRouting和配套的接口TableRoutingHandler分表路由器，由TShardingRoutingHandler来实现DataSourceRoutingHandler 和TableRoutingHandler。

2017-02-03 09:59 UTC, baihui212 commented on tsharding-client/src/main/java/com/mogujie/trade/db/DataSourceRouting.java
> +    Class<? extends MapperRoutingHandler> mapper() default MapperRoutingHandler.EmptyMapperRoutingHandler.class;
不建议在DataSourceRouting分库路由器里加分表路由的内容。建议新开一个注解TableRouting和配套的接口TableRoutingHandler分表路由器，由TShardingRoutingHandler来实现DataSourceRoutingHandler 和TableRoutingHandler。

2017-02-03 09:59 UTC, baihui212 commented on tsharding-client/src/main/java/com/mogujie/trade/db/DataSourceRouting.java
>       */
你MapperRoutingHandler类里的SchemaName方法，可以放到DataSourceRoutingHandler里。

2017-02-03 09:59 UTC, baihui212 commented on tsharding-client/src/main/java/com/mogujie/trade/tsharding/route/orm/MapperEnhancer.java
> +    private Map<String, MapperRoutingHandler> methodMapper = new HashMap<>();
命名上注意一下，建议methodMapper改为mapperHandlerMap

2017-02-03 09:59 UTC, baihui212 commented on tsharding-client/src/main/java/com/mogujie/trade/tsharding/route/orm/MapperHelperForSharding.java
> +        Map<String, MapperRoutingHandler> methodSet = new HashMap<>();
不是set了，就不要叫methodSet了吧

2017-02-03 10:27 UTC, bobxwang commented on tsharding-client/src/main/java/com/mogujie/trade/tsharding/route/orm/MapperEnhancer.java
> +    private Map<String, MapperRoutingHandler> methodMapper = new HashMap<>();
ok

2017-02-03 10:30 UTC, bobxwang commented on tsharding-client/src/main/java/com/mogujie/trade/tsharding/route/orm/MapperHelperForSharding.java
> +        Map<String, MapperRoutingHandler> methodSet = new HashMap<>();
ok

2017-02-03 10:30 UTC, bobxwang commented on tsharding-client/src/main/java/com/mogujie/trade/db/MapperRoutingHandler.java
> +    String SchemaName(Long shardingPara);
ok

2018-01-18 06:18 UTC, baihui212 commented
此分支提到的改善意见，会在TSharding2.0中一并解决。

2018-01-18 06:18 UTC, closed without merging